Add real image validator
igorkasyanchuk/active_storage_validations pull request #168
Opened 2022-10-09 22:51 UTC by kukicola

Content type validation isn't enough to ensure that what users upload is an image and can be manipulated by MiniMagick or Vips. So my idea is to add additional validator which can check if a file can be processed by the library. 

For simplicity, I used `Metadata` class which has necessary methods. It probably should be extracted to separate class but I didn't want to make a huge refactor along the way

It should solve the following issues:
https://github.com/igorkasyanchuk/active_storage_validations/issues/91
https://github.com/igorkasyanchuk/active_storage_validations/issues/62
https://github.com/igorkasyanchuk/active_storage_validations/issues/130 (partially, since it's only for images, for all other files we can extend ContentTypeValidator to read a file and use `Marcel::MimeType.for`)

2022-10-10 09:21 UTC, igorkasyanchuk commented
@gr8bit could you please help me with a review? Difficult to focus on this right now because of current situation in Ukraine

2022-10-10 10:21 UTC, gr8bit commented
Hi @kukicola, I dealt with this exact subject (I think) a few days ago and I'd like your opinion on this issue: https://github.com/rails/marcel/issues/76
I overloaded the `Marcel::MimeType.for` method in an initializer for this purpose, changing the one line from the ticket above.

2022-10-10 10:36 UTC, kukicola commented
@gr8bit I'm not sure if we should call it a Marcel issue. Those fallbacks are probably there for some reason. If it was up to me I would suggest making `for_data` public (to keep current `for` behavior) and using it in ActiveStorage instead. 

Anyway, I would treat that as a separate thing. Minetype validation is still not enough here. Consider a file with magicbytes matching PNG file but the rest of the file is garbage (corrupted image, random bytes, malicious code, whatever). Validation should also fail in this case. That's why calling `image.avg` (vips) or image.valid? (minimagick) is important here - to check if file can be processed by library

2022-10-10 12:17 UTC, gr8bit commented
@kukicola Thank you for the feedback, I'll incorporate that in the issue.
As for this PR, what I understood: you want to make sure an attachment really is a "processable image" for Vips/ImageMagick, so for types they cannot handle (might be webp or jpeg xl depending on your processor) they should fail validation. Right?

2022-10-10 12:28 UTC, kukicola commented
@gr8bit Yes but it can be used also just to check if the image is safe to display somewhere (even without processing). I agree, that `real` is not a perfect name, I was working on it late in the evening and didn't have better ideas :). What about `valid_image` to avoid suggesting that user needs to process the image?

2022-10-10 12:40 UTC, gr8bit commented
> @gr8bit Yes but it can be used also just to check if the image is safe to display somewhere (even without processing). I agree, that `real` is not a perfect name, I was working on it late in the evening and didn't have better ideas :). What about `valid_image` to avoid suggesting that user needs to process the image?

I fully understand that. :D My point of view on it is: you cannot know if the user can actually display it - it might be something that ImageMagick can handle but the user's browser (or "application") cannot (some new formats or even aged ones like Ghostscript). So I was thinking: the only thing we can ensure using Vips/IM is: they can handle it, that's why think processable might be a good fit.
In terms of "valid": all images that we can process are definitely valid - but not all valid images we can definitely process. ;)

2022-10-10 12:46 UTC, kukicola commented
ok I agree, I'll update PR to "processable" later today

2022-10-10 15:34 UTC, kukicola commented
@gr8bit done, please take a look

2022-10-10 16:10 UTC, gr8bit requested changes

2022-10-10 16:10 UTC, gr8bit commented on test/active_storage_validations_test.rb
> +    e.another_image.attach(tar_file_with_image_content_type)
I think we should add a negative test here as well, ensuring that a `processable_image: false` will accept the .tar file as png as suggested by file extension and type.

2022-10-10 16:11 UTC, gr8bit commented
> @gr8bit done, please take a look

You're fast, I tried my best to keep up. ;)

2022-10-10 16:18 UTC, kukicola commented
I have a lot of time today :) fixes done

2022-10-10 16:20 UTC, gr8bit commented
@igorkasyanchuk everything looks fine in my opinion, this PR could be merged.

2022-10-10 16:22 UTC, gr8bit approved these changes

2022-10-11 18:10 UTC, merged

2022-10-11 18:11 UTC, igorkasyanchuk commented
very good, I have checked your discussion, and to me all looks good.