Do not require attachments to be attached to use limit validator
igorkasyanchuk/active_storage_validations pull request #68
Opened 2020-04-04 19:36 UTC by neumanrq

The dummy app's `Project` class makes use of the `LimitValidator` by specifying the minimum and maximum count of attached documents:

```Ruby
class Project < ApplicationRecord
  …
  validates :documents, limit: { min: 1, max: 3 }
end
```

I noticed that one currently (without this PR) needs to add `attached: true` to employ the ` AttachedValidator` to surpass the first guard line within `LimitValidator`:

```Ruby
module ActiveStorageValidations
  class LimitValidator < ActiveModel::EachValidator # :nodoc:
    … 
    def validate_each(record, attribute, _)
      return true unless record.send(attribute).attached? # <--- Enforces the AttachedValidator
      …
    end
    …
  end
end
```
When I understood everything correctly (please correct me otherwise 🙈) then I think it's simply not necessary to do so and the `AttachedValidator` can left out here. Doing so and leaving it out makes the documented setup, that is this line:

```Ruby
validates :documents, limit: { min: 1, max: 3 }
```

work as expected. If it's not left out one would need to add `attached: true` to the above statement to make it work.

@igorkasyanchuk In case I misunderstood this and `attached: true` should be better added in such cases, just let me know!

As I expect that one does not necessarily need the `AttachedValidator` here, this PR drops the guard and fixes some test case situation, including a specific test edge case for the case of checking for the minimum value.

2020-08-18 17:52 UTC, igorkasyanchuk commented
@neumanrq sorry for a very long response just missed that

if you remove that line, can you validate that min: 0 + max: 3?

do you see any other impact with this change?

2020-08-28 06:36 UTC, neumanrq commented
Hello @igorkasyanchuk! Thanks for your feedback. By the time I proposed it, I did not see any further impact by this change. Unfortunately, as I have switched my job recently, I have no access to the repository where we used this patched version. Maybe @elalemanyo can check if there's time and if still in use?

2020-10-21 15:14 UTC, elalemanyo commented
@igorkasyanchuk We can validate that min: 0 + max: 3 and as @rstammer already said there is not impact 😊

2021-05-25 14:26 UTC, UliKuch commented
Hi @igorkasyanchuk, just wanted to ask if you plan on merging this 🙂

2022-10-13 00:57 UTC, gr8bit commented
I think this PR is quite important as it makes the limit validation much more intuitive. @rstammer @elalemanyo can one of you resolve the conflicts of this branch?

2022-10-13 06:49 UTC, rstammer commented
@gr8bit I will dive in and return with and push the updated branch!

2023-01-04 18:21 UTC, gr8bit commented
@rstammer HNY! 😃 I'd love to have this PR in the next release, would you have the time to sync and check the conflicts anytime soon?

2023-01-04 21:00 UTC, rstammer commented
Hi @gr8bit - sorry for dropping the ball here again. I will try to dive in tomorrow and fix the test file!

2023-01-08 21:23 UTC, rstammer commented
Hey @gr8bit - I've resolved the merge conflicts and fixed the tests. However, as the original idea for this arose two years ago, I'd appreciate you double-checking this to verify it's still meaningful. Thanks!! 🙌

2023-01-08 23:06 UTC, gr8bit requested changes
Thank you @rstammer!
Except for this single change everything looks fine to me. I'd really like to have this fix in 1.1.0 (new minor version as it slightly changes limit behavior).

2023-01-08 23:06 UTC, gr8bit commented on test/active_storage_validations_test.rb
> +    e.proc_documents.attach(pdf_file)
Duplicate to line 373?

2023-01-09 07:04 UTC, rstammer commented on test/active_storage_validations_test.rb
> +    e.proc_documents.attach(pdf_file)
Good catch. Thanks! Fixed now ✌️

2023-01-10 19:38 UTC, gr8bit approved these changes
All fine, thanks a lot!

2023-01-10 19:39 UTC, merged